spring.application.name=Billing Service
spring.datasource.url=jdbc:postgresql://localhost:5432/billing_db
spring.datasource.username=lakarra
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=true
